### ISSUE TITLE
Super key is not working in preferences

### ISSUE THREAD

**Issue by noirbizarre** [smmr0/gnome-reorder-workspaces#12]
Hi 👋🏼 

Great extension ! 
There is an issue with `accelRow`: it does not allow the `Super` key to be used as a composition key (I use `Super` for all DE management and I want to bind `CTRL`+`Super`+`Alt`+ `Left|Right`)

Note that after you tried to edit from the pref UI, the entry are available in `dconf` (schema is missing) and its possible to manually set it there, but the pref window don't update (doesn't seem binded), you need to close it and reopen

**Comment by smmr0** [comment]
Thanks for reporting this. Unfortunately I'm unable to reproduce it on my machine (Ubuntu Desktop 22.04). If this is still happening for you, could you send a screen recording of it and some details of your system (operating system, X11 vs Wayland, other extensions installed, etc)?

> its possible to manually set it [in `dconf`], but the pref window don't update (doesn't seem binded), you need to close it and reopen

Good to note. :+1: I don't plan to add such bindings in the preferences window; however any changes to those settings should take immediate effect (in terms of the extension's actual behavior) regardless of how they were set.

> schema is missing

This seems to be true for any extensions; it bugs me too. :sweat_smile:
