### ISSUE TITLE
Not working/installing

### ISSUE THREAD

**Issue by catpreneur** [smmr0/gnome-reorder-workspaces#13]
![image](https://user-images.githubusercontent.com/46097282/176009123-30a7c0f6-2781-4c32-aa63-28c064b25d29.png)

On ubuntu 22.04. was working fine before i upgraded (don't know what version i was on before)

**Comment by smmr0** [comment]
Does the issue persist after logging out & back in or after a reboot? I've seen this happen when upgrading other extensions too; I think it may be a GNOME Shell issue rather than an issue with any particular extension.

**Comment by catpreneur** [comment]
log out and back in did the the trick thanks
