### ISSUE TITLE
Feature request: Indicate order position when not in overview

### ISSUE THREAD

**Issue by thyttan** [smmr0/gnome-reorder-workspaces#20]
Thanks for this extension, I think it will be useful to me! :)

I have a feature request, not super important but would be neat.

When switching between workspaces outside of the overview, Gnome Shell (ver. 44) uses indicator dots that pops up. I'd like it if these were presented in the same way when reordering with this extension.

**Comment by smmr0** [comment]
This was a wonderful idea; thank you. :slightly_smiling_face: It is being released in [v18](https://github.com/smmr0/gnome-reorder-workspaces/releases/tag/v18).
