### ISSUE TITLE
works only ctrl+super+up (sometimes this neither).... and doesn't work the ctrl+super+down.

### ISSUE THREAD

**Issue by All3xJ** [smmr0/gnome-reorder-workspaces#23]
when ctrl+super+up doesn't work neither, you can disable and reenable the extension and seems to work again.

I have GNOME 45

**Comment by smmr0** [comment]
Can you please provide the following information?

- Version of this extension that you have installed
- Screenshot of this extension's preferences/settings window
- Operating system and version
- GNOME Shell version 45.0 or 45.1?
- Can you confirm that this issue is not because of another extension interfering?

**Comment by All3xJ** [comment]
> Can you please provide the following information?
> 
>     * Version of this extension that you have installed
> 
>     * Screenshot of this extension's preferences/settings window
> 
>     * Operating system and version
> 
>     * GNOME Shell version 45.0 or 45.1?
> 
>     * Can you confirm that this issue is not because of another extension interfering?

I've always had this problem.

Reorder Workspaces v 22
![image](https://github.com/smmr0/gnome-reorder-workspaces/assets/20903913/40cdb463-f0ac-49fa-b7d6-3cee33986626)

Fedora 39(had also in other versions)
GNOME 45.1 (had also in other versions)
disabling extensions does not seem to interfere. It's quiet random.

**Comment by OsoRojo** [comment]
I also see this on Fedora 39 using Wayland.  ctrl+super+up works.  Down does not.

**Comment by All3xJ** [comment]
I think I fixed just by changing the shortcut in the extension settings.
