### ISSUE TITLE
Error on Fedora 33

### ISSUE THREAD

**Issue by almereyda** [smmr0/gnome-reorder-workspaces#4]
When activating the extension on Fedora 33, an error is displayed and the action fails.

```
 OS: Fedora 
 Kernel: x86_64 Linux 5.9.10-200.fc33.x86_64
 DE: GNOME 3.38.2
```

**Comment by smmr0** [comment]
I can't reproduce this issue on a fresh Fedora 33 virtual machine with Linux kernel 5.9.11-200.fc33.x86_64 and GNOME Shell 3.38.2. Can you provide more detail about the error and list what other extensions you have installed?

**Comment by almereyda** [comment]
Actually, yes, this is working again magically. Yet a new glitch popped up: When scrolling horizontally with four fingers, the screen of the adjacent workspace is not scrolled together with the current anymore, but suddenly pops up when the scroll finishes.

**Comment by smmr0** [comment]
What extensions or settings do you have configured that allow you to scroll horizontally? Also does that happen every time you scroll or only the first time after you enable the extension?
