### ISSUE TITLE
how about gnome 40 support?

### ISSUE THREAD

**Issue by vsudakov** [smmr0/gnome-reorder-workspaces#7]
I didn't test your extension with Gnome 40 actually yet.
But I noticed that Gnome 40 is not listed in metadata.json https://github.com/jeremiahmegel/gnome-reorder-workspaces/blob/4310c0dfd7f9498a465432f6531620ff8f7c00ac/src/metadata.json#L8-L11

btw - well done! this is a "must have" extension for me! thank you very much!

**Comment by ashy1227** [comment]
just tested it out, it's as easy as just changing the shell-version to 40.0

i might open a PR later. i'm not an expert at gnome shell extensions though, so it probably would be better if someone with actual experience changed it. this plugin has a **lot** of potential, honestly should just be in gnome by default. probably the feature i'd most want besides gnome 40 support would be dragging workspaces with the mouse

**Comment by smmr0** [comment]
resolved via <https://github.com/jeremiahmegel/gnome-reorder-workspaces/commit/772d93430ce1f7e322b6af5c278efea2dcffad92>, which is being released in [v7](https://github.com/jeremiahmegel/gnome-reorder-workspaces/releases/tag/v7)

**Comment by ashy1227** [comment]
you're amazing thanks for coming back and updating this :D
