### ISSUE TITLE
gnome 41 support

### ISSUE THREAD

**Issue by All3xJ** [smmr0/gnome-reorder-workspaces#9]
You just need to add "40" to "shell-version" array inside metadata.json

**Comment by smmr0** [comment]
resolved via <https://github.com/jeremiahmegel/gnome-reorder-workspaces/commit/772d93430ce1f7e322b6af5c278efea2dcffad92>, which is being released in [v7](https://github.com/jeremiahmegel/gnome-reorder-workspaces/releases/tag/v7)
